# TEST HTTP requests
### use with: REST Client extension
@apiurl = http://localhost:3000/api

### items.js


### GET all items
GET {{apiurl}}/items


### get item with id 1
GET {{apiurl}}/items/1


### add new item
POST {{apiurl}}/items
Content-type: application/json

{"name": "mandariini", "weight": 86}

### delete item with id 2
DELETE {{apiurl}}/items/2

### update item with id 3
PUT {{apiurl}}/items/3
Content-type: application/json

{"name": "updated kivi"}


### users.js


### GET all users
GET {{apiurl}}/users

### Get user with id 4 (joni)
GET {{apiurl}}/users/4

### Add new user
POST {{apiurl}}/users
Content-Type: application/json

{
  "name": "Matti Meikäläinen",
  "email": "matti.meikalainen@hotmail.com"
}
### update
PUT {{apiurl}}/users/1
Content-Type: application/json

{
  "name": "Juhani Päivitetty",
  "email": "juhani.uusi@yahoo.com"
}
### deletoidaan jesse
DELETE {{apiurl}}/users/6
